Allow any combination of input format and output format.
BlockchainCommons/bc-seedtool-cli pull request #69
Opened 2022-05-01 13:44 UTC by Sjlver

There's no technical reason why this shouldn't be allowed.

Closes https://github.com/BlockchainCommons/seedtool-cli/issues/63

2022-05-02 18:26 UTC, wolfmcnally requested changes
You need to add many more tests to prove that any input format to any output format also work.

2022-05-02 20:47 UTC, Sjlver commented
> You need to add many more tests to prove that any input format to any output format also work.

That's a bit of a high standard, considering that there were no tests before ;-)

Anyway, I've added a testcase that tests all meaningful combinations of input/output formats. Let me know what you think.

The test might actually have discovered a bug; shouldn't the output of these two commands be the same? Note that the checksum words are different.

```shell
$ src/seedtool --deterministic TEST | src/seedtool --deterministic TEST --out sskr
tuna acid epic gyro many meow able able able next edge lamb liar city girl draw visa roof logo jolt city waxy jury trip dark safe arch flew what
$ src/seedtool --deterministic TEST | src/seedtool --deterministic TEST --in hex --out sskr
tuna acid epic gyro edge next able able able next edge lamb liar city girl draw visa roof logo jolt city waxy jury trip dark loud song main atom
```

2022-05-02 21:01 UTC, ChristopherA commented
> > You need to add many more tests to prove that any input format to any output format also work.
> 
> That's a bit of a high standard, considering that there were no tests before ;-)
> 
> Anyway, I've added a testcase that tests all meaningful combinations of input/output formats. Let me know what you think.

I believe all the tests are here: https://github.com/BlockchainCommons/seedtool-cli/blob/master/src/test.sh

2022-05-15 08:18 UTC, Sjlver commented
I have fixed the test now.
What I had thought to be a bug was actually not a bug, just an artifact of using the same deterministic seed in two invocations of seedtool-cli.

@wolfmcnally what do you think? Would this be good enough or do you need more tests than that?

2025-02-14 18:51 UTC, Sjlver commented
I'm planning to close this PR. I still think it makes sense, but since there is no progress, I'm abandoning it.

It you ever feel like supporting this and continuing the work on seedtool.info, let me know.

2025-02-14 18:52 UTC, closed without merging